// Generated database types for Supabase
// This would typically be generated by `supabase gen types typescript`

export interface Database {
  public: {
    Tables: {
      families: {
        Row: {
          id: string;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          auth_user_id: string | null;
          family_id: string;
          email: string;
          role: 'parent_a' | 'parent_b';
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id?: string | null;
          family_id: string;
          email: string;
          role: 'parent_a' | 'parent_b';
          name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string | null;
          family_id?: string;
          email?: string;
          role?: 'parent_a' | 'parent_b';
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      children: {
        Row: {
          id: string;
          family_id: string;
          name: string;
          color: string;
          icon: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          name: string;
          color?: string;
          icon?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          name?: string;
          color?: string;
          icon?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          family_id: string;
          title: string;
          notes: string | null;
          due_date: string | null;
          recurrence_rule: string | null;
          assignee_user_id: string | null;
          type: 'cyclical' | 'project';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          title: string;
          notes?: string | null;
          due_date?: string | null;
          recurrence_rule?: string | null;
          assignee_user_id?: string | null;
          type: 'cyclical' | 'project';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          title?: string;
          notes?: string | null;
          due_date?: string | null;
          recurrence_rule?: string | null;
          assignee_user_id?: string | null;
          type?: 'cyclical' | 'project';
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          family_id: string;
          title: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          title: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          title?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      availability_blocks: {
        Row: {
          id: string;
          user_id: string;
          start_time: string;
          end_time: string;
          type: 'work' | 'childcare' | 'personal';
          is_recurring: boolean;
          recurrence_pattern: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          start_time: string;
          end_time: string;
          type: 'work' | 'childcare' | 'personal';
          is_recurring?: boolean;
          recurrence_pattern?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          start_time?: string;
          end_time?: string;
          type?: 'work' | 'childcare' | 'personal';
          is_recurring?: boolean;
          recurrence_pattern?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      weekly_totals: {
        Row: {
          id: string;
          user_id: string;
          week_start: string;
          work_minutes: number;
          childcare_minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week_start: string;
          work_minutes?: number;
          childcare_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          week_start?: string;
          work_minutes?: number;
          childcare_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      integration_accounts: {
        Row: {
          id: string;
          family_id: string;
          provider: 'google_calendar' | 'google_maps';
          account_email: string;
          calendars: any; // JSONB
          access_token: string | null;
          refresh_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          provider: 'google_calendar' | 'google_maps';
          account_email: string;
          calendars?: any; // JSONB
          access_token?: string | null;
          refresh_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          provider?: 'google_calendar' | 'google_maps';
          account_email?: string;
          calendars?: any; // JSONB
          access_token?: string | null;
          refresh_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      homebase_event_map: {
        Row: {
          id: string;
          task_id: string;
          google_event_id: string;
          calendar_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          google_event_id: string;
          calendar_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          google_event_id?: string;
          calendar_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}